export const GET_MOVIE_LIST  = 'GET_MOVIE_LIST';
export const GET_MOVIE_DETAIL = 'GET_MOVIE_DETAIL';
export const SET_CURRENT_MOVIE = 'SET_CURRENT_MOVIE';
export const CLEAR_MOVIE_STATE = 'CLEAR_MOVIE_STATE';
export const SUCCESS = 'SUCCESS';
export const FAILED = 'FAILED';